### ISSUE TITLE
Conventions

### ISSUE THREAD

**Issue by JustDaile** [GlobalDevelopmentOrg/VMT#10]
- Camel-Casing on method, variable/field names.
- use (this) keyword when referring to instance variables see below
. . . 
public String getName(){
   return this.name;
}
. . .
It will help if we follow the same conventions. If we always use this when referring to instance variables it will make the code more readable. We don't need to look around to see where that variable was created, we are already being told explicitly it is an instance variable. Follow these conventions will help for this reason, in more complex classes at-least. However being consistent will help a lot.

**Comment by hibroseph** [comment]
Thanks! I quickly adjusted the code and repushed it right before class! Tell me how it looks now just to make sure I am on the correct path!

**Comment by hibroseph** [comment]
Hold your horses, I missed some for the this. let me repush

**Comment by hibroseph** [comment]
Okay! Pushed the new commit. Check it out and tell me what you think! Thanks!

**Comment by JustDaile** [comment]
It all likes good to me
