### ISSUE TITLE
I messed up while writing the documentation on the classes

### ISSUE THREAD

**Issue by JustDaile** [GlobalDevelopmentOrg/VMT#11]
@Author and @Since should both be lowercase.
Seeing as you have an active branch could you fix them and add yourself to the documentation.
Also don't forget to do the same for the classes you have made, only add yourself. It will just be helpful in future to see who worked on what classes and features. Thanks.

**Comment by hibroseph** [comment]
What do you mean add myself to the documentation?

**Comment by hibroseph** [comment]
You are talking about me using javadocs on the classes that I make?

**Comment by JustDaile** [comment]
just for class description, author and since. this will help to keep track
