### ISSUE TITLE
Package your classes

### ISSUE THREAD

**Issue by JustDaile** [GlobalDevelopmentOrg/VMT#12]
Try not to leave random classes in the project root, try organise your code into packages. Named as appropriately as possible. vehicle.maintenance.tracker.models in a MVC design pattern would make sense.

**Comment by hibroseph** [comment]
Take a look at my new commit.

Does this mean that most the source code should go in the models package or should we create a lot of subpackages in the models package, IE, should I make another package called core truck which holds the Part and Truck or should they reside in just the models package?

**Comment by JustDaile** [comment]
no its more to package similar concepts that to separate everything. models will be things that will be passed to views. truck and part are models. so that makes sense. we could have many different models they can all go in that package. don't worry to much about it. things can be moved.

**Comment by JustDaile** [comment]
you'll get used to it. they is no right way. just helps.
