### ISSUE TITLE
Field and Variable placement

### ISSUE THREAD

**Issue by JustDaile** [GlobalDevelopmentOrg/VMT#13]
All variables/fields show be placed at the top of the class
public class Good {
     int a;
     int b;
     // construct
     // methods
}
public class Bad {
    // construct
    int a;
    // method
    int b;
    // method
}
in the Good class example we can see all types and members Good will use
in the Bad class example we have to look around and in-between methods to find where if at all these are declared.

**Comment by hibroseph** [comment]
Take a look at this but I am pretty sure I am good now. If not, resubmit an issue, Thanks!
