### ISSUE TITLE
Implementation Idea

### ISSUE THREAD

**Issue by JustDaile** [GlobalDevelopmentOrg/VMT#14]
I was thinking that for the parts we could have a maintenance id, then have a model for maintenance schedule that can be found using the maintenance id for that specific part. The vehicle could also have a maintenance id. This way we could add multiple scheduled checks for each part and each vehicle individually.

This scheduled task (maintenance date) could allow comments or notes. It will consist of a time in the future when this task should be checked. I think this is a good idea. Let me know your thoughts and I will iron out the details and see what I can come up with. 

It has a few perks I can think of, i'd like to know your thoughts.

**Comment by hibroseph** [comment]
I'm understanding it at a very high level but I think it would be a good feature to have. It will just give us more possibilities in the end so might as well.

**Comment by hibroseph** [comment]
This maintenance id would be different for every part and truck as soon as they're instantiated or be added as we schedule a maintenance manually?

**Comment by JustDaile** [comment]
Well initially if a user creates a Vehicle (Truck) they will be no maintenance scheduled. Same with a Part. However we can allow the client to be able to attach/link/create a maintenance (thing/class/object) and we will save that in another table on the database. This maintenance class will have an id (partId, vehicleId) to which it belongs. One or the other, not both. We will have to think of a good, descriptive name for such a variable, Also for the class/model itself.

**Comment by hibroseph** [comment]
Okay, so you're thinking of creating a maintenance class that is instantiated when the client adds a maintenance request (say we need to repair the clutch on truck 4), and that maintenance request is attached to either the part or the truck. (If it's attached to a specific part, the specific part is attached to the vehicle because of the vehicle ID) Then there will be a database that holds all of the scheduled maintenance (maintenance objects that we have instantiated) 

Am I on the right track?

**Comment by JustDaile** [comment]
Well adding the task to the vehicle if it is a task for the part doesn't sound like a good idea. If the part is updated the task becomes void. However the task would be attached to the vehicle so we would have no way of ensuring it was removed when the part was changed/updated/removed. I think if we have a generic maintenance task we should just bind it to either a part or vehicle. I am just thinking now though that the Id for the task would be not be able to distinguish if its meant for a part or a vehicle. So we will or you can see what ideas you can come up with to solve that problem.

**Comment by JustDaile** [comment]
I guess one way to solve this would both part and vehicle have an array of scheduled task ids. We could put these ids in the same table as the class. If we concatenate the values (comma separated) we can have a single column in both part and vehicles table for taskIds.
When we load either we simply use the java string split method to chop the array into individual ids.
Maybe cast them to ints, some error checking/validation. We would still, then be able to have a separate table for scheduled tasks.
