### ISSUE TITLE
Model and their implementation

### ISSUE THREAD

**Issue by hibroseph** [GlobalDevelopmentOrg/VMT#15]
In the MVC design structure, we obviously have put vehicles and parts in the models package, the C means control, meaning it will handle all the control between the core models (vehicles) and the data base correct? 

Just to understand at a high level, what else is going to be inside of models

**Comment by JustDaile** [comment]
We don't want to over-complicate the package structure really. Just simple packaging will do. I suppose they are conventions we could follow. However if it makes sense then its good enough at this point. Feel free to add or even change packages at this time. Its not really a major problem.
